apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: abc-onboarding

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - redis-deployment.yaml
  - rabbitmq-deployment.yaml
  - minio-deployment.yaml
  - application-deployment.yaml
  - application-service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: onboarding
  app.kubernetes.io/part-of: abc-bank
  app.kubernetes.io/managed-by: kustomize
